version: "3.8"
services:
  php:
    image: my-php
    container_name: cphp
    build:
      context: ./php
    environment:
      MYSQL_PASSWORD: 1234
    volumes: 
      - ./my_web_dir:/usr/share/my_web/php

  nginx:
    image: my-nginx
    container_name: cngx
    build:
      context: ./nginx
    ports:
      - "80:2420"
    volumes: 
      - ./my_web_dir:/usr/share/my_web/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  mariadb:
    image: mariadb
    container_name: cdb
    restart: always
    volumes:
      - mariadb-data:/bitnami/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  phpmyadmin:
    image: my-phpmyadmin
    container_name: cadm
    build: 
      context: ./phpmyadmin
    ports: 
      - "8080:80"
    environment:
      PMA_HOST: cdb

volumes: 
  mariadb-data: