version: "3"
services:
  php:
    image: my-php
    container_name: cphp
    build:
      context: .
      dockerfile: Dockerfile-php
    environment:
      MYSQL_PASSWORD: 1234
    volumes: 
      - ./my_web_dir:/usr/share/my_web/php

  nginx:
    image: my-nginx
    container_name: cngx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:2420"
    volumes: 
      - ./my_web_dir:/usr/share/my_web/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

  mariadb:
    image: mariadb
    container_name: cdb
    restart: always
    volumes:
      - mariadb-data:/bitnami/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234

volumes: 
  mariadb-data:
